name: Release

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display secrets
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          echo "${{ secrets.SSH_HOST }}"
          echo "${{ secrets.SSH_USERNAME }}"
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
          echo $SSH_HOST

      - name: SSH to server and run command
        uses: appleboy/ssh-action@v0.0.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Logged in to server"
